#set style line 1 lt 1 lw 8
#set style line 2 lt 3 lw 8
#set style line 3 lt 1 lw 2
#set style line 4 lt 3 lw 2
#set style line 5 lt 0 lw 8
#set style line 6 lt 0 lw 4


#FIGS 1-4  PSS variants: blind,healer,swapper,mix
set pointsize 2
set style line 1 lt 1 lc rgb "black" lw 4 pt 9 ps 2
set style line 2 lt 2 lc rgb "black" lw 4 pt 11 ps 2
set style line 3 lt 3 lc rgb "red"   lw 4 pt 13 ps 2
set style line 4 lt 4 lc rgb "blue" lw 4 pt 8 ps 1.8

set style line 5 lt 2 lc rgb "black" lw 4 pt 10 ps 1.8
set style line 6 lt 2 lc rgb "black" lw 4 pt 12 ps 2

set style line 7 lt 1 lc rgb "black" lw 4 pt 6 ps 1.8
set style line 8 lt 1 lc rgb "black" lw 4 pt 3 ps 1.8
set style line 9 lt 2 lc rgb "black" lw 4 pt 4 ps 1.5

#set style line 8 lt 3 lw 2 pt 6
#set style line 9 lt 0 lw 2 pt 12

set style line 13 lt 5 lc rgb "black" lw 4 pt 14 ps 2


# LINESTYLE USED IN FILLEDCURVES PLOTS
set style line 10 lt 1 lc rgb "black" lw 1
set style arrow 1 nohead ls 10

set style line 11 lt 1 lc rgb "#CCCCCC" lw 3
set style arrow 2 nohead ls 11

set style line 12 lt 1 lc rgb "#888888" lw 4

#LINESTYLE for CHURN TRACES
set style line 20 lt 1 lc rgb "black" lw 0.5

set style line 30 lt 1 lc rgb "black" lw 0.1


#set linetype  1 lc rgb "dark-violet" lw 1
#set linetype  2 lc rgb "#009e73" lw 1
#set linetype  3 lc rgb "#56b4e9" lw 1
#set linetype  4 lc rgb "#e69f00" lw 1
#set linetype  5 lc rgb "#f0e442" lw 1
#set linetype  6 lc rgb "#0072b2" lw 1
#set linetype  7 lc rgb "#e51e10" lw 1
#set linetype  8 lc rgb "black"   lw 1
#set linetype  9 lc rgb "gray50"  lw 1



#STYLES FOR MAP
set style line 400 lt 1 lc rgb "grey" 			lw 2
set style line 40 lt 1 lc rgb "black" 			lw 0.05 pt 7 ps 0.15
set style line 41 lt 1 lc rgb "red" 		   	lw 0.05 pt 7 ps 0.15
set style line 42 lt 1 lc rgb "blue" 	        lw 0.05 pt 7 ps 0.15
set style line 43 lt 1 lc rgb "EE82EE"         	lw 0.05 pt 7 ps 0.15
set style line 44 lt 1 lc rgb "#009e73"		 	lw 0.05 pt 7 ps 0.15
set style line 45 lt 1 lc rgb "#56b4e9"		 	lw 0.05 pt 7 ps 0.15
set style line 46 lt 1 lc rgb "#e69f00"		 	lw 0.05 pt 7 ps 0.15
set style line 47 lt 1 lc rgb "#f0e442"		 	lw 0.05 pt 7 ps 0.15
set style line 48 lt 1 lc rgb "#0072b2"		 	lw 0.05 pt 7 ps 0.15
set style line 49 lt 1 lc rgb "#e51e10"		 	lw 0.05 pt 7 ps 0.15
set style line 50 lt 1 lc rgb "black"  		 	lw 0.05 pt 7 ps 0.15
set style line 51 lt 1 lc rgb "FF1493"    		lw 0.05 pt 7 ps 0.15
set style line 52 lt 1 lc rgb "FFD700" 			lw 0.05 pt 7 ps 0.15
set style line 53 lt 1 lc rgb "E6E6FA" 			lw 0.05 pt 7 ps 0.15
set style line 54 lt 1 lc rgb "20B2AA" 			lw 0.05 pt 7 ps 0.15
set style line 55 lt 1 lc rgb "800000" 			lw 0.05 pt 7 ps 0.15
set style line 56 lt 1 lc rgb "3CB371" 			lw 0.05 pt 7 ps 0.15


#DIFFERENT COLORS FOR LINES USED IN PERCENTILES
set style line 105 lt 1 lc rgb "#404040" lw 1 pt 9 ps 2
set style line 125 lt 1 lc rgb "#595959" lw 1 pt 9 ps 2 
set style line 150 lt 1 lc rgb "#808080" lw 1 pt 9 ps 2 
set style line 175 lt 1 lc rgb "#A6A6A6" lw 1 pt 9 ps 2 
set style line 190 lt 1 lc rgb "#D9D9D9" lw 1 pt 9 ps 2 

set style line 101 lt 1 lc rgb "black" lw 2
set style line 102 lt 1 lc rgb "black" lw 6
set style line 103 lt 2 lc rgb "black" lw 2
set style line 104 lt 2 lc rgb "black" lw 6

# style for number of packets (small dashed)
set style line 200 lt 21 lc rgb "black" lw 2
